name: flutter_riverpod_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^15.1.2
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  dio_http_formatter: ^3.3.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  retrofit_generator: ^9.2.0
  json_serializable: ^6.9.5
  freezed: ^3.0.6
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
